### ISSUE TITLE
NumPy Error when working with LCD

### ISSUE THREAD

**Issue by MrCampbellDuchess** [pimoroni/enviroplus-python#100]
when running any example using the LCD in python3 (python3 lcd.py), this is the result:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lcd.py", line 3, in <module>
    import ST7735
  File "/usr/local/lib/python3.7/dist-packages/ST7735-0.0.4-py3.7.egg/ST7735/__init__.py", line 23, in <module>
    import numpy as np
  File "/usr/local/lib/python3.7/dist-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/usr/local/lib/python3.7/dist-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "/usr/bin/python3"
  * The NumPy version is: "1.19.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory
```

I can run the same example with python2 correctly, but not 3.x.

This was installed using both the install.sh and, just for good measure, the one-line install method.

**Comment by MrCampbellDuchess** [comment]
Solved, sounds like an issue with NumPy, solved with

sudo apt-get install libatlas-base-dev
