### ISSUE TITLE
Failed to read PMS5003 (fresh latest install)

### ISSUE THREAD

**Issue by sphaero** [pimoroni/enviroplus-python#119]
Just installed a fresh latest raspberry pi os (bullseye) with the required software. Everything seem to work except for the PMS5003

```
2022-11-18 12:54:50.782 INFO     particulates.py - Print readings from the PMS5003 particulate sensor.

Press Ctrl+C to exit!


Traceback (most recent call last):
  File "/home/ect/src/enviroplus-python/examples/particulates.py", line 24, in <module>
    readings = pms5003.read()
  File "/usr/local/lib/python3.9/dist-packages/pms5003/__init__.py", line 127, in read
    raise SerialTimeoutError("PMS5003 Read Timeout: Failed to read start of frame byte")
pms5003.SerialTimeoutError: PMS5003 Read Timeout: Failed to read start of frame byte
```

**Comment by sphaero** [comment]
Ok I feel stupid. Should read better. The PMS5003 is an additional sensor apparently.
