### ISSUE TITLE
(pms5003) Not working on Pi Zero / Bookworm

### ISSUE THREAD

**Issue by andypiper** [pimoroni/enviroplus-python#139]
Updated to the latest from GitHub.

Updated to the current Raspberry Pi OS.

Examples that access the PMS5003 are not able to run.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
$ uname -a
Linux zero-enviro 6.6.28+rpt-rpi-v6 #1 Raspbian 1:6.6.28-1+rpt1 (2024-04-22) armv6l GNU/Linux
```

However...

```
$ ./all-in-one.py
2024-04-26 14:07:04.703 INFO     all-in-one.py - Displays readings from all of Enviro plus' sensors

Press Ctrl+C to exit!


Traceback (most recent call last):
  File "/home/andypiper/Pimoroni/enviroplus/examples/./all-in-one.py", line 41, in <module>
    pms5003 = PMS5003()
              ^^^^^^^^^
  File "/home/andypiper/.virtualenvs/pimoroni/lib/python3.11/site-packages/pms5003/__init__.py", line 109, in __init__
    self._pin_enable, self._pin_reset = gpiodevice.get_pins_for_platform(PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 0)
```

Additional info:

```
$ gpioinfo
gpiochip0 - 54 lines:
	line   0:     "ID_SDA"       unused   input  active-high
	line   1:     "ID_SCL"       unused   input  active-high
	line   2:      "GPIO2"       unused   input  active-high
	line   3:      "GPIO3"       unused   input  active-high
	line   4:      "GPIO4"       unused   input  active-high
	line   5:      "GPIO5"       unused   input  active-high
	line   6:      "GPIO6"       unused   input  active-high
	line   7:      "GPIO7"   "spi0 CS1"  output   active-low [used]
	line   8:      "GPIO8"   "spi0 CS0"  output   active-low [used]
	line   9:      "GPIO9"       unused   input  active-high
	line  10:     "GPIO10"       unused   input  active-high
	line  11:     "GPIO11"       unused   input  active-high
	line  12:     "GPIO12"       unused   input  active-high
	line  13:     "GPIO13"       unused   input  active-high
	line  14:     "GPIO14"       unused   input  active-high
	line  15:     "GPIO15"       unused   input  active-high
	line  16:     "GPIO16"       unused   input  active-high
	line  17:     "GPIO17"       unused   input  active-high
	line  18:     "GPIO18"       unused   input  active-high
	line  19:     "GPIO19"       unused   input  active-high
	line  20:     "GPIO20"       unused   input  active-high
	line  21:     "GPIO21"       unused   input  active-high
	line  22:     "GPIO22"       unused   input  active-high
	line  23:     "GPIO23"       unused   input  active-high
	line  24:     "GPIO24"       unused   input  active-high
	line  25:     "GPIO25"       unused   input  active-high
	line  26:     "GPIO26"       unused   input  active-high
	line  27:     "GPIO27"       unused   input  active-high
	line  28:       "SDA0"       unused   input  active-high
	line  29:       "SCL0"       unused   input  active-high
	line  30:       "CTS0"       unused   input  active-high
	line  31:       "RTS0"       unused   input  active-high
	line  32:       "TXD0"       unused   input  active-high
	line  33:       "RXD0"       unused   input  active-high
	line  34:    "SD1_CLK"       unused   input  active-high
	line  35:    "SD1_CMD"       unused   input  active-high
	line  36:  "SD1_DATA0"       unused   input  active-high
	line  37:  "SD1_DATA1"       unused   input  active-high
	line  38:  "SD1_DATA2"       unused   input  active-high
	line  39:  "SD1_DATA3"       unused   input  active-high
	line  40:  "CAM_GPIO1"       unused  output  active-high
	line  41:      "WL_ON"       unused  output  active-high
	line  42:         "NC"       unused   input  active-high
	line  43:   "WIFI_CLK"       unused   input  active-high
	line  44:  "CAM_GPIO0" "cam1_regulator" output active-high [used]
	line  45:      "BT_ON"   "shutdown"  output  active-high [used]
	line  46: "HDMI_HPD_N"        "hpd"   input   active-low [used]
	line  47: "STATUS_LED_N" "ACT" output active-low [used]
	line  48:   "SD_CLK_R"       unused   input  active-high
	line  49:   "SD_CMD_R"       unused   input  active-high
	line  50: "SD_DATA0_R"       unused   input  active-high
	line  51: "SD_DATA1_R"       unused   input  active-high
	line  52: "SD_DATA2_R"       unused   input  active-high
	line  53: "SD_DATA3_R"       unused   input  active-high
```

[insert shrugging Elmo GIF here]

**Comment by helgibbons** [comment]
Might be worth trying `pip install --upgrade gpiodevice` and `pip install --upgrade pms5003` to make sure you're on the most recent versions - there's been a bunch of updates to both over the last few days!

**Comment by andypiper** [comment]
OK! Thanks for the tip here.
This took me from gpiodevice 0.0.4 -> 0.0.5 and pms5003 1.0.0 -> 1.0.1

Now I'm seeing...

```
./particulates.py
2024-04-29 13:03:09.054 INFO     particulates.py - Print readings from the PMS5003 particulate sensor.

Press Ctrl+C to exit!


Traceback (most recent call last):
  File "/home/andypiper/.virtualenvs/pimoroni/lib/python3.11/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyAMA0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andypiper/enviroplus-python/examples/./particulates.py", line 19, in <module>
    pms5003 = PMS5003()
              ^^^^^^^^^
  File "/home/andypiper/.virtualenvs/pimoroni/lib/python3.11/site-packages/pms5003/__init__.py", line 103, in __init__
    self.setup()
  File "/home/andypiper/.virtualenvs/pimoroni/lib/python3.11/site-packages/pms5003/__init__.py", line 109, in setup
    self._serial = serial.Serial(self._device, baudrate=self._baudrate, timeout=4)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andypiper/.virtualenvs/pimoroni/lib/python3.11/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/home/andypiper/.virtualenvs/pimoroni/lib/python3.11/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyAMA0: [Errno 2] No such file or directory: '/dev/ttyAMA0'
```

Failing on a serial device (which indeed is not there) when running the PMS5003 related stuff.

**Comment by Gadgetoid** [comment]
From the long, long tedious install instructions which I wouldn't read either - 

And if you're using a PMS5003 sensor you will need to:

### Bookworm

* Enable serial: `raspi-config nonint do_serial_hw 0`
* Disable serial terminal: `raspi-config nonint do_serial_cons 1`
* Add `dtoverlay=pi3-miniuart-bt` to your `/boot/config.txt`

### Bullseye

* Enable serial: `raspi-config nonint set_config_var enable_uart 1 /boot/config.txt`
* Disable serial terminal: `sudo raspi-config nonint do_serial 1`
* Add `dtoverlay=pi3-miniuart-bt` to your `/boot/config.txt`


(though ymmv on these, raspi-config has changed somewhat and broken my expectations!)

**Comment by andypiper** [comment]
thank you. I suspect it was less me deliberately not reading, and more, I'd done it before so didn't re-read for the new setup.

I definitely already had `dtoverlay=pi3-miniuart-bt` (in `/boot/firmware/config.txt`) so it looks like the two `raspi-config` steps there were somehow not applied.

I'm a silly person, and I appreciate your help! WE HAVE PARTICULATES!

**Comment by Gadgetoid** [comment]
> I'd done it before so didn't re-read for the new setup.

Story of my life, that!

Thanks for confirming it's up and running, and that we haven't just released a broken mess 😆
